### ISSUE TITLE
Milestone Checklists

### ISSUE THREAD

**Issue by Almagnus1** [Almagnus1/IaconClient#2]
Current State is: Beta

The following needs to be completed before we are in Beta:
- [x] Configurations for mods not in the pack have been trimmed
- [x] Only one type of each ore available, preventing multiple ingots/dusts for the same ore
- [x] Start screen customization pass
- [x] Mods for the Server and Client are in sync
- [x] Implement $$MC_VER$$ and $$MP_VER$$ processing in the build scripts

Once we are in Beta:
- [x] Modpack is hosted on Curse

The following needs to be completed before we are released:
- [ ] Modpack Icon should be the Iacon icon
- [ ] Modpack is locked upon install
- [ ] Verify that everything can be made, which includes the following:
- [ ] Applied Energistics
- [ ] BiblioCraft
- [ ] Big Reactors
- [ ] Botania
- [ ] Buildcraft
- [ ] Carpenter's Blocks
- [ ] Chisel
- [ ] ComputerCraft
- [ ] EnderIO
- [ ] Ender Storage
- [ ] EnderTech
- [ ] ExtraUtilities
- [ ] Funky Locomotion
- [ ] Hat Stands
- [ ] Iron Chests
- [ ] Jabba
- [ ] Minefactory Reloaded
- [ ] Modular Powersuits
- [ ] Mystcraft
- [ ] ObsidiPlates
- [ ] OpenBlocks
- [ ] Pam's Harvestcraft
- [ ] Portal Gun
- [ ] Project Red
- [ ] Railcraft
- [ ] Redstone Arsenal
- [ ] Simply Jetpacks
- [ ] Steve's Factory Manager
- [ ] Thaumcraft
- [ ] Thaumic Energistics
- [ ] Thaumic Exploration
- [ ] Thaumic Tinkerer
- [ ] The Twilight Forest
- [ ] Thermal Dynamics
- [ ] Thermal Expansion
- [ ] Tinkers Construct
- [ ] Tinker's Mechworks
- [ ] Translocators
- [ ] WR-CBE-Universal (aka Wireless Redstone)

**Comment by Almagnus1** [comment]
Recent commit added $$MC_VER$$ and $$MP_VER$$ processing in the build scripts

**Comment by Almagnus1** [comment]
Recent server commit synchronized mods with the current client.

**Comment by Almagnus1** [comment]
Very vanilla main menu added with last set of updates.

**Comment by Almagnus1** [comment]
Tracker for the last Alpha objective is at https://github.com/Almagnus1/IaconClient/issues/9

**Comment by Almagnus1** [comment]
Flattening ore gen is too high risk of a change, and would likely take a very long time to get sorted correctly.  https://github.com/Almagnus1/IaconClient/issues/14 was created to handle that task.

I'm doing some final experiments that should help make the client easier to submit to Curse, and once those are done, we're in Beta.

**Comment by Almagnus1** [comment]
We're on Curse! \o/ http://minecraft.curseforge.com/projects/iacon-modpack
